# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de8124037c8ef1aa4fade405565791a8326cb066a31aea2eb1a0e59beb3e1fe8d6cb0b8e89ddb64547764401528e8e35b70d4ae06e007b9b97ce6cd687878479

test:
  secret_key_base: d33fb30da7aca3a0f5a3838749c6b55d2190149ff3717db11e61f1ce8ac82d0e4bbda0aaef0baf413b91910aa7d91ae8b4fc706c980d16640bc5b91042aaa677

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
